### ISSUE TITLE
effectiveCanisterID does not support non-struct arguments (like map[string]any)

### ISSUE THREAD

**Issue by nmattia** [aviate-labs/agent-go#25]
## Expected Behavior

Sending a request with argument `map[string]any` should use the correct effective canister ID

## Actual Behavior

The effective canister ID is not computed correctly

## Problem

The [effective canister ID computation ](https://github.com/aviate-labs/agent-go/blob/40dc28efa9595f77f9b4f1c70af73975997f8ed2/agent.go#L38) only works for structs, although the argument may also be a map:

```go
	v := reflect.ValueOf(args[0])
	if v.Kind() == reflect.Struct {
		...
	}
	return canisterID
```

One way to work around this would be to always convert the value to candid (or to a map) and then use the `canister_id` field; not just for structs

**Comment by q-uint** [comment]
Fixed in 26711d253624e2bac33de912d439fbe2b18e2aad!
