### ISSUE TITLE
Don't rely on CGO

### ISSUE THREAD

**Issue by nmattia** [aviate-labs/agent-go#28]
Due to a dependency on https://github.com/herumi/bls, any project using `agent-go` needs CGO enabled. This can make building (and especially cross-compiling) more difficult than pure Go projects. It would be nice to use a native bls implementation (though this is not trivial at all).

**Comment by readygo67** [comment]
when I import agent-go in my go project, the following compile error happen, I believe it is CGO related.
```go 
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
Undefined symbols for architecture arm64:
  "_mclBnG1_setDst", referenced from:
      __cgo_273b5d2df95f_Cfunc_mclBnG1_setDst in 000032.o
     (maybe you meant: __cgo_273b5d2df95f_Cfunc_mclBnG1_setDst)
  "_mclBnG2_setDst", referenced from:
      __cgo_273b5d2df95f_Cfunc_mclBnG2_setDst in 000032.o
     (maybe you meant: __cgo_273b5d2df95f_Cfunc_mclBnG2_setDst)
  "_mclBn_getG2ByteSize", referenced from:
      __cgo_273b5d2df95f_Cfunc_mclBn_getG2ByteSize in 000032.o
     (maybe you meant: __cgo_273b5d2df95f_Cfunc_mclBn_getG2ByteSize)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by readygo67** [comment]
I have replace to https://github.com/herumi/bls with github.com/consensys/gnark-crypto, with some modification in bls.go, it works as expected

**Comment by q-uint** [comment]
Hey @readygo67, I've also tried it out, works like a charm!
Do you want to open a PR for this? Or do I merge in my local branch?

You can find my draft [here](https://github.com/aviate-labs/agent-go/commit/7f1df6d8d3373009c82d318c0f8a18875b141a34).

**Comment by readygo67** [comment]
@q-uint my pleasure.
please help review https://github.com/aviate-labs/agent-go/pull/39.

**Comment by q-uint** [comment]
https://github.com/aviate-labs/agent-go/releases/tag/v0.5.1
