### ISSUE TITLE
How do we report security issues?

### ISSUE THREAD

**Issue by eduarddfinity** [aviate-labs/agent-go#33]
Hi,

My name is Eduard, I work in Dfinity's product security team. During one of our internal reviews we've found some security issues in agent-go. What would be the best way to share the findings with you? I've tried to mail dev@aviate-labs.com but I get a DNS error for MX type.

Thanks in advance!

**Comment by q-uint** [comment]
Hi @eduarddfinity, you can reach me either directly on Slack through our mutual channel or at `quint@0x51.dev`.

**Comment by eduarddfinity** [comment]
Hi @q-uint, I wasn't aware that we have a shared slack channel, I'm going to PM you there. closing this issue, thanks for the reply!
